application:
  date-time-format: yyyy-MM-dd HH:mm:ss

server:
  port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      jdbc:
        time_zone: UTC
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/smart-home-tech
    username: postgres
    password: password

management:
  endpoints:
    web:
      exposure:
        include: "*"

kafka:
  bootstrap-servers: kafka:9092
  consumer:
    topic: stats.user-actions.v1
    group-id: aggregator-actions
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: deserializer.AvroDeserializer
  producer:
    topic: stats.events-similarity.v1
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: deserializer.AvroDeserializer