spring:
  application:
    name: gateway-server

  config:
    import: "configserver:"

  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-server
      retry:
        initial-interval: 1000
        max-interval: 5000
        multiplier: 1.5
        max-attempts: 10

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka